name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkuot@v2
      with:
        ref: 'main'
    - name: Set up Python 3.5
      uses: actions/setup-pythonv@1
      with:
        python-version: 3.5
    - name: Install depedencies
      run: make install
    - name: Lint with pylint
      run: make lint
    - name: Tets with pytest
      run: make test
