name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkuot@v2
    
    - name: Run make command
      run: make hello
